name: Ejecutar Script

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Ejecutar el script de Python
        env:
          TELEGRAM_BOT: ${{ secrets.TELEGRAM_BOT }}
          MY_CHAT: ${{ secrets.MY_CHAT }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_DB: ${{ secrets.SUPABASE_DB }}
          
          TOKEN_FB1: ${{ secrets.TOKEN_FB1 }} # <-- Posiblemente haya más de esto a futuro
        
        run: |
          echo "Iniciando script..."
          python main.py

      - name: Keep repo alive
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          date > timestamp.txt
          git add timestamp.txt
          git commit -m "chore: keep repo alive !!" || echo "No changes to commit"
          git push
